const API = window.MESPREX_API_BASE || '';
const fallback = [
  { id: 1, logoUrl: 'mesprex-logo.jpg', name: 'Painel Grátis #01', link: 'https://example.com/painel-gratis-01', description: 'Um painel gratuito para você começar sem gastar nada. Veja a prévia antes de entrar.', demoImageUrl: 'https://placehold.co/1200x760/171310/ff7a1a?text=PREVIA+PAINEL+GRATIS+01', active: true },
  { id: 2, logoUrl: 'mesprex-logo.jpg', name: 'Painel Grátis #02', link: 'https://example.com/painel-gratis-02', description: 'Outra opção liberada para a comunidade, com imagem de demonstração do painel.', demoImageUrl: 'https://placehold.co/1200x760/20150f/ffd06a?text=PREVIA+PAINEL+GRATIS+02', active: true },
  { id: 3, logoUrl: 'mesprex-logo.jpg', name: 'Painel Grátis #03', link: 'https://example.com/painel-gratis-03', description: 'Escolha seu próximo painel grátis e veja como ele funciona antes de acessar.', demoImageUrl: 'https://placehold.co/1200x760/100f0e/ff9d4d?text=PREVIA+PAINEL+GRATIS+03', active: true }
];
function localItems() { try { return JSON.parse(localStorage.getItem('mesprex-buttons')) || fallback; } catch { return fallback; } }
async function load() { try { const res = await fetch(`${API}/api/buttons`); if (!res.ok) throw new Error(); const data = await res.json(); return data.items?.length ? data.items : localItems(); } catch { return localItems(); } }
function render(items) { const active = items.filter(item => item.active !== false); document.querySelector('#count').textContent = `${String(active.length).padStart(2, '0')} PAINÉIS DISPONÍVEIS`; document.querySelector('#links').innerHTML = active.map((item, i) => `<a class="link" href="${item.link}" target="_blank" rel="noreferrer" style="animation-delay:${i * 80}ms"><small>0${i + 1}</small><span class="avatar" data-preview="${i}"><img src="${item.demoImageUrl || item.logoUrl || 'mesprex-logo.jpg'}" alt="Prévia de ${item.name}"></span><span class="copy"><strong>${item.name}</strong><em>${item.description}</em><mark>▧ PRÉVIA DO PAINEL</mark></span><b>↗</b></a>`).join('') || '<div class="empty">Nenhum painel publicado ainda.</div>'; document.querySelectorAll('[data-preview]').forEach(node => node.addEventListener('click', event => { event.preventDefault(); const item = active[Number(node.dataset.preview)]; document.querySelector('#modalImage').src = item.demoImageUrl || item.logoUrl || 'mesprex-logo.jpg'; document.querySelector('#modalTitle').textContent = item.name; document.querySelector('#modalDescription').textContent = item.description; document.querySelector('#modalLink').href = item.link; document.querySelector('#previewModal').classList.remove('hidden'); })); }
load().then(render);
document.querySelector('#share').addEventListener('click', async () => { await navigator.clipboard?.writeText(location.href); document.querySelector('#share').textContent = '✓ Copiado'; setTimeout(() => document.querySelector('#share').textContent = '⌘ Compartilhar', 1600); });
document.querySelector('#closePreview').addEventListener('click', () => document.querySelector('#previewModal').classList.add('hidden')); document.querySelector('#previewModal').addEventListener('click', event => { if (event.target.id === 'previewModal') event.currentTarget.classList.add('hidden'); });
